version: '3.8'
services:
  mariadb:
    container_name: mariadb
    image: mariadb:inception
    build: /home/nflan/inception/srcs/requirements/mariadb
    healthcheck:
      test: ["CMD", "mysql", "--user=${DATABASE_USER}", "--password=${DATABASE_UPASS}", "wordpress" ]
      interval: 2s
      timeout: 2s
      retries: 20
    volumes:
      - database:/var/lib/mysql
    networks:
      - myeverything
    env_file:
      .env
  wordpress:
    container_name: wordpress
    image: wordpress:inception
    depends_on:
      mariadb:
        condition: service_healthy
    build: /home/nflan/inception/srcs/requirements/wordpress
    env_file:
      .env
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - myeverything
    healthcheck:
      test: ["CMD", "service", "php7.4-fpm", "status"]
      interval: 4s
      timeout: 4s
      retries: 40
  nginx:
    container_name: nginx
    image: nginx:inception
    build: /home/nflan/inception/srcs/requirements/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - myeverything
    depends_on:
      wordpress:
        condition: service_healthy
  
  adminer:
    container_name: adminer
    image: adminer:inception
    depends_on:
      mariadb:
        condition: service_healthy
    build: /home/nflan/inception/srcs/requirements/bonus/adminer
    env_file:
      .env
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - myeverything
  cadvisor:
    container_name: cadvisor
    image: cadvisor:inception
    build: /home/nflan/inception/srcs/requirements/bonus/cadvisor
    volumes:
      - wordpress-data:/var/www/html
      - database:/var/lib/mysql
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - myeverything

networks:
  myeverything:

volumes:
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      device: "/home/nflan/data/wordpress"
      o: bind
  database:
    driver: local
    driver_opts:
      type: none
      device: "/home/nflan/data/mariadb"
      o: bind
