version: '3.8'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:inception
    build: requirements/mariadb
    healthcheck:
        test: ["CMD", "mysql", "--user=${DATABASE_USER}", "--password=${DATABASE_UPASS}", "wordpress" ]
        interval: 2s
        timeout: 2s
        retries: 20
    volumes:
        - database:/var/lib/mysql
    networks:
        - myeverything
    env_file:
        .env

  wordpress:
    container_name: wordpress
    image: wordpress:inception
    depends_on:
      mariadb:
        condition: service_healthy
    build: requirements/wordpress
    environment:
        - BONUS=1
    env_file:
        .env
    volumes:
        - wordpress-data:/var/www/html
    networks:
        - myeverything
    healthcheck:
      test: ["CMD", "service", "php7.4-fpm", "status"]
      interval: 4s
      timeout: 4s
      retries: 40

  nginx:
    container_name: nginx
    image: nginx:inception
    build: requirements/nginx
    environment:
        - BONUS=1
    env_file:
        .env
    ports:
        - "443:443"
    volumes:
        - wordpress-data:/var/www/html
    networks:
        - myeverything
    depends_on:
      wordpress:
        condition: service_healthy

  adminer:
    container_name: adminer
    image: adminer:inception
    depends_on:
      wordpress:
        condition: service_healthy
    build: requirements/bonus/adminer
    env_file:
        .env
    volumes:
        - wordpress-data:/var/www/html
    networks:
        - myeverything
  
  cadvisor:
    container_name: cadvisor
    image: cadvisor:inception
    privileged: true
    depends_on:
      wordpress:
        condition: service_healthy
    build: requirements/bonus/cadvisor
    volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
    ports:
        - "8080:8080"
    networks:
        - myeverything

  redis:
    container_name: redis
    image: redis:inception
    depends_on:
      wordpress:
        condition: service_healthy
    build: requirements/bonus/redis
    sysctls:
        - net.core.somaxconn=512
    env_file:
        .env
    networks:
        - myeverything
    volumes:
        - redis-vol:/var/lib/redis

  flask:
    container_name: flask
    image: flask:inception
    build: requirements/bonus/flask
    env_file:
        .env
    volumes:
        - wordpress-data:/var/www/html
    networks:
        - myeverything

  proftpd:
    container_name: proftpd
    image: proftpd:inception
    build: requirements/bonus/proftpd
    depends_on:
      wordpress:
        condition: service_healthy
    env_file:
        .env
    ports:
      #   - "20:21"
        - 127.0.0.1:21:21
          #  - 0.0.0.0:20:20
    volumes:
        - wordpress-data:/wordpress
    networks:
        - myeverything

networks:
    myeverything: {}

volumes:
  wordpress-data:
    driver_opts:
      type: none
      device: "/home/nflan/data/wordpress"
      o: bind

  database:
    driver_opts:
      type: none
      device: "/home/nflan/data/mariadb"
      o: bind

  redis-vol:
    driver_opts:
      type: none
      device: "/home/nflan/data/redis"
      o: bind
