version: '3.1'
services:
  nginx:
    build: /home/nflan/inception/srcs/requirements/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress-data:/var/www/html/nflan.42.fr
    networks:
      - myeverything
    depends_on:
      wordpress:
        condition: service_healthy
  wordpress:
    depends_on:
      mariadb:
        condition: service_healthy
    build: /home/nflan/inception/srcs/requirements/wordpress
    environment:
      - nflan.42.fr
    volumes:
      - wordpress-data:/var/www/html/nflan.42.fr
    networks:
      - myeverything
    healthcheck:
      test: ["CMD", "test", "-f", "/var/www/html/nflan.42.fr/wp-config.php"]
      interval: 4s
      timeout: 4s
      retries: 20
  mariadb:
    build: /home/nflan/inception/srcs/requirements/mariadb
    healthcheck:
      test: ["CMD", "mysql", "--user=nflan42", "--password=nflan42", "wordpress"]
      interval: 2s
      timeout: 2s
      retries: 20
    volumes:
      - database:/var/lib/mysql
    networks:
      - myeverything

networks:
  myeverything:

volumes:
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      device: "/home/nflan/data/wordpress"
      o: bind
  database:
    driver: local
    driver_opts:
      type: none
      device: "/home/nflan/data/mariadb"
      o: bind
