version: '3.8'
services:
  mariadb:
    build: /home/nflan/inception/srcs/requirements/mariadb
    healthcheck:
      test: ["CMD", "mysql", "--user=${DATABASE_USER}", "--password=${DATABASE_UPASS}", "wordpress" ]
      interval: 2s
      timeout: 2s
      retries: 20
    volumes:
      - database:/var/lib/mysql
    networks:
      - myeverything
    environment:
        DATABASE_WP: $DATABASE_WP
        DATABASE_PASSWORD: $DATABASE_PASSWORD
        DATABASE_ADM: $DATABASE_ADM
        DATABASE_USER: $DATABASE_USER
        DATABASE_UPASS: $DATABASE_UPASS
  wordpress:
    depends_on:
      mariadb:
        condition: service_healthy
    build: /home/nflan/inception/srcs/requirements/wordpress
    environment:
        DATABASE: $DATABASE
        DATABASE_WP: $DATABASE_WP
        DATABASE_PASSWORD: $DATABASE_PASSWORD
        DATABASE_USER: $DATABASE_USER
        DATABASE_UPASS: $DATABASE_UPASS
        WORDPRESS_WEBSITE_TITLE: $WORDPRESS_WEBSITE_TITLE
        WORDPRESS_WEBSITE_URL_WITHOUT_HTTP: $WORDPRESS_WEBSITE_URL_WITHOUT_HTTP
        WORDPRESS_WEBSITE_URL: $WORDPRESS_WEBSITE_URL
        WORDPRESS_ADMIN_USER: $WORDPRESS_ADMIN_USER
        WORDPRESS_ADMIN_PASSWORD: $WORDPRESS_ADMIN_PASSWORD
        WORDPRESS_ADMIN_EMAIL: $WORDPRESS_ADMIN_EMAIL
        WP_USER2: $WP_USER2
        WP_UPASS2: $WP_UPASS2
        WP_UEMAIL2: $WP_UEMAIL2
    volumes:
      - wordpress-data:/var/www/html/nflan.42.fr
    networks:
      - myeverything
    healthcheck:
      test: ["CMD", "service", "php7.4-fpm", "status"]
      interval: 4s
      timeout: 4s
      retries: 40
  nginx:
    build: /home/nflan/inception/srcs/requirements/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress-data:/var/www/html/nflan.42.fr
    networks:
      - myeverything
    depends_on:
      wordpress:
        condition: service_healthy
  
  adminer:
    build: /home/nflan/inception/srcs/requirements/bonus/adminer
    environment:
        DATABASE_WP: $DATABASE_WP
        DATABASE_USER: $DATABASE_USER
        DATABASE_UPASS: $DATABASE_UPASS
    networks:
      - myeverything

networks:
  myeverything:

volumes:
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      device: "/home/nflan/data/wordpress"
      o: bind
  database:
    driver: local
    driver_opts:
      type: none
      device: "/home/nflan/data/mariadb"
      o: bind
